myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='homepage'),
    path('about/', views.about, name='about'),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path('', views.posts_list, name='posts'),
    path('new-post/', views.post_new, name='new-post'),
    path('post/<slug:slug>/', views.post_page, name='page'),
    path('post/<slug:slug>/edit/', views.post_edit, name='edit'),
    path('<slug:slug>/delete/', views.post_delete, name='delete'),
]

myblog/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

myblog/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from autoslug import AutoSlugField

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = AutoSlugField(populate_from='title', unique=True, max_length=200, always_update=False)
    date = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.title

myblog/users/models.py
from django.db import models

# Create your models here.

myblog/posts/forms.py
from django import forms
from .models import Post

class CreatePost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "body", "banner"]

myblog/myblog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse("This is my homepage")
    return render(request, "home.html")

def about(request):
    # return HttpResponse("This is my about page")
    return render(request, "about.html")

myblog/posts/views.py
from ast import Delete
from django.shortcuts import redirect, render
from .models import Post
from django.contrib.auth.decorators import login_required
from .forms import CreatePost

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', { 'posts': posts })

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', { 'post': post })

@login_required(login_url="users:login")
def post_new(request):
    if request.method == "POST":
        form = CreatePost(request.POST, request.FILES)
        if form.is_valid():
            newpost = form.save(commit=False)
            newpost.author = request.user
            newpost.save()
            return redirect('posts:posts')
    else:
        form = CreatePost()
    return render(request, 'posts/post_new.html', { 'form': form })

@login_required(login_url="users:login")
def post_edit(request, slug):
    post = Post.objects.get(slug=slug)

    if request.user != post.author:
        return redirect('posts:posts')
    
    if request.method == "POST":
        form = CreatePost(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:posts')
    else:
        form = CreatePost(instance=post)
    return render(request, 'posts/post_edit.html', { 'form': form})

@login_required(login_url="users:login")
def post_delete(request, slug):
    post = Post.objects.get(slug=slug)

    if request.user == post.author:
        
        post.delete()
        return redirect('posts:posts')

myblog/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:posts")
    else:   
        form = UserCreationForm()
    return render(request, "users/register.html", { "form": form })

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())

            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:posts")
        
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", { "form": form })

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("posts:posts")

myblog/posts/templates/posts/post_edit.html
{% extends "base.html" %}

{% block title %}
    Edit post
{% endblock title %}

{% block content %}
    <h1>Edit post</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-3">Update</button>
    </form>  
{% endblock content %}

myblog/posts/templates/posts/post_new.html
{% extends "base.html" %}

{% block title %}
    New Post
{% endblock title %}

{% block content %}
    <section>
        <form class="form-with-validation" action="{% url "posts:new-post" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit btn btn-success mt-2">Add Post</button>
        </form> 
    </section>
{% endblock content %}

myblog/posts/templates/posts/post_page.html
{% extends "base.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    <section>
        <h1>{{ post.title }}</h1>
        <img src="{{ post.banner.url }}" alt="{{ post.title }}" 
            class="img-fluid rounded shadow-lg d-block mx-auto mb-4 banner-img"/>
        <p>{{ post.body }}</p>
        <p>
            
            {% if post.last_updated > post.date %}
                <em class="text-success ms-2">edited</em>
                on {{ post.last_updated }}
            {% else %}
                Posted on {{ post.date }}
            {% endif %}

        </p> 

        {% if request.user == post.author %}
            <a href="{% url 'posts:edit' slug=post.slug %}" class="btn btn-success"> Edit Post</a>
            <a href="{% url 'posts:delete' slug=post.slug %}" class="btn btn-danger"> Delete Post</a>
        {% endif %}
    </section>    
{% endblock content %}

myblog/posts/templates/posts/posts_list.html
{% extends "base.html" %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <section>
        <h1 class="bg-danger text-white p-2 text-center rounded">Treding Now</h1>
        
        {% for post in posts %}
            <article class= "post">
                <h2>
                    <a href="{% url 'posts:page' slug=post.slug %}">
                        {{ post.title }}
                    </a>
                </h2>           
                <p>{{ post.body|truncatechars:100 }}</p>
                <p>{{ post.date }} by {{ post.author }}</p>
            </article>
        {% endfor %}
        
    </section>
    
{% endblock content %}

myblog/templates/about.html
{% extends "base.html" %}

{% block title %}
    About
{% endblock title %}

{% block content %}
    <h1>About</h1>
    <h1>Check my <a href="{% url 'homepage' %}">Home</a> page</h1>
{% endblock content %}

myblog/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django Blog App
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
</head>
<body class="fs-6">

    <nav class="navbar navbar-dark py-0.5">
        <div class="navbar-nav d-flex flex-row gap-3 ms-auto ms-3 me-3 fs-5">
            {% with request.resolver_match.url_name as current %}
                {% if user.is_authenticated %}
                    <a class="nav-link {% if current == 'about' %}active{% endif %}" href="{% url 'about' %}">About</a>
                    <a class="nav-link {% if current == 'posts' %}active{% endif %}" href="{% url 'posts:posts' %}">Posts</a>
                    <a class="nav-link {% if current == 'New Post' %}active{% endif %}" href="{% url 'posts:new-post' %}">New Post</a>
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button class="logout-button nav-link {% if current == 'logout' %}active{% endif %}">Logout</button>
                    </form>
                {% else %}
                    <a class="nav-link {% if current == 'homepage' %}active{% endif %}" href="{% url 'homepage' %}">Home</a>
                    <a class="nav-link {% if current == 'login' %}active{% endif %}" href="{% url 'users:login' %}">Login</a>
                    <a class="nav-link {% if current == 'register' %}active{% endif %}" href="{% url 'users:register' %}">Register</a>
                {% endif %}
            {% endwith %}
        </div>   
    </nav>

    <main class="mt-2">
        {% block content %}
        
        {% endblock content %}
    </main>

    <script src="{% static 'js/main.js' %}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>

myblog/templates/home.html
{% extends "base.html" %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <div class="d-flex flex-column justify-content-center align-items-center">
        <h1 class="bg-danger text-white p-2 text-center rounded">Welcome to Kenyan Buzz</h1>   
        <h2 class="text-black p-3 text-center">Create an account or Login to create a post</h2>
        <div class="d-flex flex-column justify-content-center align-items-center">
            <h4 ><a href="{% url "users:login" %}">Login</a></h4>
            <h4><a href="{% url "users:register" %}">Register</a></h4>
        </div> 
    </div>
{% endblock content %}

myblog/users/templates/users/login.html
{% extends "base.html" %}

{% block title %}
    User Login
{% endblock title %}

{% block content %}

    <div class="login-form">
        <h2 class="login-account">User Login</h2>
        <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}"/>
            {% endif %}
            <button class="btn btn-success mt-2 form-submit">Login</button>
        </form>
    </div>

{% endblock content %}

myblog/users/templates/users/register.html
{% extends "base.html" %}

{% block title %}
    Create An Account
{% endblock title %}

{% block content %}
<div class="d-flex justify-content-center align-items-center">
    <div class="form-container">
        <h2 class="register-account">Create An Account</h2>
        <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="btn btn-success mt-2 form-submit">Register</button>
        </form>
    </div>
</div>
{% endblock content %}